apiVersion: v1
kind: Service
metadata:
  name: usermanagement-redis-service
spec:
  selector:
    app: usermanagement-redis
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
